//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shouter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shouter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add station.
        /// </summary>
        public static string addStation {
            get {
                return ResourceManager.GetString("addStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizing file....
        /// </summary>
        public static string analizingFile {
            get {
                return ResourceManager.GetString("analizingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizing link: {0}....
        /// </summary>
        public static string analizingLink {
            get {
                return ResourceManager.GetString("analizingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shouter.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering....
        /// </summary>
        public static string buffering {
            get {
                return ResourceManager.GetString("buffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved successfully.
        /// </summary>
        public static string changesSavedSuccessfully {
            get {
                return ResourceManager.GetString("changesSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose PLS file.
        /// </summary>
        public static string choosePlsDialog {
            get {
                return ResourceManager.GetString("choosePlsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string connecting {
            get {
                return ResourceManager.GetString("connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection lost or the addres is not valid.
        /// </summary>
        public static string connectionLostWrongAddress {
            get {
                return ResourceManager.GetString("connectionLostWrongAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find station&apos;s name. Set it in &quot;Main data&quot; tab.
        /// </summary>
        public static string couldNotFindName {
            get {
                return ResourceManager.GetString("couldNotFindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete station.
        /// </summary>
        public static string deleteStation {
            get {
                return ResourceManager.GetString("deleteStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this station?.
        /// </summary>
        public static string deleteStationQuestion {
            get {
                return ResourceManager.GetString("deleteStationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit station.
        /// </summary>
        public static string editStation {
            get {
                return ResourceManager.GetString("editStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error.
        /// </summary>
        public static string fatalError {
            get {
                return ResourceManager.GetString("fatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File read..
        /// </summary>
        public static string fileRead {
            get {
                return ResourceManager.GetString("fileRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From PLS file.
        /// </summary>
        public static string fromPlsFile {
            get {
                return ResourceManager.GetString("fromPlsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting station name....
        /// </summary>
        public static string gettingStationName {
            get {
                return ResourceManager.GetString("gettingStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address.
        /// </summary>
        public static string invalidAddress {
            get {
                return ResourceManager.GetString("invalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string licenses {
            get {
                return ResourceManager.GetString("licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is invalid..
        /// </summary>
        public static string linkInvalid {
            get {
                return ResourceManager.GetString("linkInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is valid..
        /// </summary>
        public static string linkIsValid {
            get {
                return ResourceManager.GetString("linkIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file.
        /// </summary>
        public static string loadFile {
            get {
                return ResourceManager.GetString("loadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main data.
        /// </summary>
        public static string mainData {
            get {
                return ResourceManager.GetString("mainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray.
        /// </summary>
        public static string minimizeToTray {
            get {
                return ResourceManager.GetString("minimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to tray instead of quitting.
        /// </summary>
        public static string minimizeTraySettings {
            get {
                return ResourceManager.GetString("minimizeTraySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string mute {
            get {
                return ResourceManager.GetString("mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name found..
        /// </summary>
        public static string nameFound {
            get {
                return ResourceManager.GetString("nameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing: {0}.
        /// </summary>
        public static string playing_station {
            get {
                return ResourceManager.GetString("playing_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLS file.
        /// </summary>
        public static string plsFile {
            get {
                return ResourceManager.GetString("plsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any working link. Try changing PLS file or fill the data manually in &quot;General data&quot; tab..
        /// </summary>
        public static string plsNoResults {
            get {
                return ResourceManager.GetString("plsNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path or link to PLS file.
        /// </summary>
        public static string plsPathLink {
            get {
                return ResourceManager.GetString("plsPathLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading PLS file....
        /// </summary>
        public static string readingPls {
            get {
                return ResourceManager.GetString("readingPls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string ready {
            get {
                return ResourceManager.GetString("ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save stations.
        /// </summary>
        public static string saveStations {
            get {
                return ResourceManager.GetString("saveStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        public static string unmute {
            get {
                return ResourceManager.GetString("unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have got unsaved changes. Do you really want to quit?.
        /// </summary>
        public static string unsavedChangesWarning {
            get {
                return ResourceManager.GetString("unsavedChangesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating link....
        /// </summary>
        public static string validatingLink {
            get {
                return ResourceManager.GetString("validatingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string view {
            get {
                return ResourceManager.GetString("view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
